services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - 3306:3306
  dbproxy:
    build:
      context: ./
      dockerfile: ./dbproxy/Dockerfile
    command: npm run dev
    depends_on:
      - db
    volumes:
      - .:/usr/app/
      - /usr/app/dbproxy/node_modules
    ports:
      - ${DBPROXY_PORT}:${DBPROXY_PORT}
    environment:
      MYSQL_URL: "jdbc:mysql://localhost:3306/${MYSQL_DATABASE}"
      DB_PASSWORD: "${DB_PASSWORD}"