services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
  dbproxy:
    build: ./src
    ports:
      - 8080:8080
    environment:
      MYSQL_URL: "jdbc:mysql://localhost:3306/mydb"